### ISSUE TITLE
GDESS_SAVEPATH in configuration file not liked

### ISSUE THREAD

**Issue by simonom** [E3SM-Project/gdess#5]
Hi gdess,

I'm using Anaconda Prompt on Windows 11.  I activate the environment for gdess. 

Regarding Step 3 in the Example section of README.  After successfully following Steps 1 and 2, I execute the recommended command for Step 3.  I get the following error:

configparser.InterpolationMissingOptionError: Bad value substitution: option 'value' in section 'save_path' contains an interpolation key 'GDESS_SAVEPATH' which is not a valid option name. Raw value: '${GDESS_SAVEPATH}'

Do you have any suggestions how to resolve?

Kind regards,
Simon O'Meara

**Comment by dkauf42** [comment]
Hi Simon!

Have you already configured and run the `set_path_vars.sh` script (described in the _Configuration_ section of the readme)?

If you've already done that, then perhaps there is a discrepancy in the path formatting, such as backward- or forward-slashes, for Windows vs. Linux.  For example, `${path_to_repo}/tests/test_data/globalview/` (Linux) changed to `${path_to_repo}\tests\test_data\globalview\` (Windows).  Could you try replacing those slashes in the `./co2_diag/bin/set_path_vars.sh` file and re-running it?  

Another potentially relevant thing, is that if you're setting these environments from a Windows command line (i.e., in cmd.exe), it might need to use `set` instead also: e.g., `set GDESS_SAVEPATH=${path_to_repo}\outputs\`.

If that's the issue, then perhaps a separate Windows version of that short script should be included alongside the Linux version.

(Unfortunately, I don't have a Windows OS to test this.)

-Danny

**Comment by simonom** [comment]
Thanks, will try these suggestions Thursday 14th April, and update you

**Comment by simonom** [comment]
I have a resolution:
I could not find a way to run a .sh file on Windows that would affect the environment variables.
However a .bat (batch) file can (such as the attached).  The order of steps to use it is:
i) set the GDESS_REPO variable at the command line in Windows:

> set GDESS_REPO=state_your_path_here

ii) run the batch file:

> call co2_diag/bin/set_path_vars.bat

This then sets the required variables ready for Step 3 of Example in README, which can be confirmed by executing 

> set

at the command line, and viewing the relevant variables in the printed list
[set_path_vars.zip](https://github.com/E3SM-Project/gdess/files/8490134/set_path_vars.zip)

**Comment by dkauf42** [comment]
@simonom, this is great!  Thank you for explaining how you resolved the variable-setting on Windows. 
If you don't mind, I will include this .bat file in the repo and update the readme.

**Comment by dkauf42** [comment]
The `set_path_vars.bat` file has been added into the repo now (commit 61819eb5d8cf9e7a7e260de8121da0a9df128e7e)
